version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      # ... steps for building/testing app ...
      # build and push Docker image
      - run:
          name: Run tests
          command: |
            set -x
            ./runtests.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
